spring:
  datasource:
    url: jdbc:mysql://rdsssafyd207.cxs0eci2yne0.ap-northeast-2.rds.amazonaws.com/tripeer
    username: RDSssafyD207
    password: d207d207
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: none

  #Oauth2 login info
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-name: kakao
            client-id :
            client-secret:
            redirect-uri:
            authorization-grant-type: authorization_code
            scope:
            client-authentication-method: client_secret_post
          google:
            client-name: google
            client-id: ENC(zt9rp8PvfHINvV324BZrxC2f4trOzi/3mjTEHkewatIAqWHDRrmCrxz32T1kLeGCjO+EvsP/JIfKJVcoXhgOb1vJw+3dSoH27h9+dTByn0YLrkNVkH3gdw==)
            client-secret: ENC(1dDGzLzNk0NfDj6lHhAPwn6HxBRfDINBLY9L3y7llfRo8VJV4EJFr93WT0K1sMis)
            redirect-uri: ENC(I2cenrUhHDogIbrfkOhtvs+v6ct/WI9jx6rCf5FD2P7q3zNh457AoRsZsdEqaKdvIL5iejnSlAVcGGyyNvL6Yw==)
            authorization-grant-type: authorization_code
            scope: ENC(swr/kCkxUhD2O0tWdTG7r813ln5avtM7)

    #JWT Time 300min, 600min
    jwt:
      access: 18000000
      refresh: 36000000
      secret: tmp


  application:
    name: tripeer
