server:
  servlet:
    context-path: /api

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  datasource:
    url: ENC(O+6cd1DEPib/iu/hkn5SAWTMEKzAmV6xq+cqOjhR4rRka0UVt6VGVSL0uLG2i2c61l/2FP5EApg=)
    username: ENC(9m9o70ex2187SXtUNb1JQA==)
    password: ENC(Wstc5/so3a0smxXFvZP5pvCfQhdj10v007R2AGIcNY8=)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 30

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: none # 엔티티 변경 시 데이터베이스 업데이트

  #Oauth2 login info
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
        registration:
          kakao:
            client-name: kakao
            client-id : ENC(IaY6SQ0O/qVmqqwYfxphw2mNp3r82EjyJv62hGoqZfuFTM8rR7LUSqFWbxYS6x48)
            client-secret: ENC(lQlOiocOvFAtDivr/RySShuAQozGv1F6o1J6tf7uYxTeXxpl9BRgPUbvbDq69cix)
            redirect-uri: https://k10d207.p.ssafy.io/api/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-authentication-method: client_secret_post
          naver:
            client-name: naver
            client-id: ENC(6aRNPfKQdE/V+vszoh/xjRRmQiu8BHABuzs/t7DfYhQ=)
            client-secret: ENC(bjVify3O4qIWMbRrfzIpbj0P7Zm2uMpw)
            redirect-uri: https://k10d207.p.ssafy.io/api/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
          google:
            client-name: google
            client-id: ENC(sSX1umy4qajs8dX/VNp+Bvujw2PRjPcloD+s9GqSyUn8zRPfAh47doTxN2XPMO0Il+Nr48H280Ysd5Q/9hYpoSH+0ZzLJxXKeBWWNk+WiNlINJyc5SHHmQ==)
            client-secret: ENC(DTVN2JEtEbU8nBY0TJqMhfgkJG1cF+Gs/GNSIZ8Yd9j0q8PLkJnpEBP7FOGsS4cw)
            redirect-uri: https://k10d207.p.ssafy.io/api/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email

    #JWT Time 300min, 600min
  jwt:
    access: 18000000
    refresh: 36000000
    secret: ENC(+TMgIEAtgPTpRvh8SSGMLDPoaEzVbkBA8RFQBsNplM5IAmNxrATCqM9itNRpS5BX)


  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(uLqb3uehjijt61z7bAolNDjE09x45e3laC0Vk26yIxA=)
    password: ENC(zhltywasMCbEhvwOVrmZJOXzsrK5B4weLd1RlrmRqQI=)
    debug: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true

odsay:
  apikey: ENC(WY4s6rkLclxdcAy0yC5Qzkz5srAwLMT1XChs29iWl59GKBggZbQW4isM/Lx75BVXfvIVkk4poNc=)

tmap:
  apikey: ENC(rq3bzD3hCoL+f1r9F3T1wYmAo6G7Y8UVawUT/x/0oYjUGj8gv8dgBByIo5YNDKOmKxYXlYqdBv8=)

kakao:
  apikey: ENC(P5ANnJgP83n706xcwZbbxZT5bg5Eypnt5peqQURgUOZoJ1llLhpq/8iJeS4iUF4l)

weather:
  apikey: ENC(/KMRGTnKpN+JVY7DwV8+Dt2GryLXkyd7j8gbTgWCl5p8p0P253PUobcm+s2BV6+jyzkxMPEjzzucQgCZiijtALp6aTHD/PeOhWbLkPmJkRrb9qVAotLJuSUvL+RuFqzWBleCf5gCtnJ8psbLhnwBsg==)

cloud:
  aws:
    credentials:
      accessKey: ENC(MDEIv0Elsed+UziTOhX2wkJGzw5jldwD0qxnjRVePpA=)
      secretKey: ENC(UZXZhURI7oZXplXNSYhkH0hUN0+rMIG4DkqDXvp2kufY5tY3UCv+hj3IRrvEnHrOxACeK2+jIRI=)
    s3:
      bucketName: tripeer207
    region:
      static: ap-northeast-2
  cloudformation:
    auto: false

  application:
    name: tripeer

